sudo: required
language: android
jdk:
  - oraclejdk8

android:
  components:
  - tools
  - build-tools-28.0.3
  - android-28
  - platform-tools
  - extra-google-m2repository
  - extra-android-m2repository
  - extra-android-support

# Only create build on Pushes to Master or Pull Requests.
branches:
  only:
    - master

# Disable emails entirely
notifications:
  email: false

before_cache:
  # Do not cache a few Gradle files/directories (see https://docs.travis-ci.com/user/languages/java/#Caching)
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    # Android SDK
    - $HOME/android-sdk-dl
    - $HOME/android-sdk

    # Gradle dependencies
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

    # Android build cache (see http://tools.android.com/tech-docs/build-cache)
    - $HOME/.android/build-cache

before_install:
  - openssl aes-256-cbc -K $encrypted_675e3fe85ff5_key -iv $encrypted_675e3fe85ff5_iv
    -in signingConfigs.gradle.enc -out signingConfigs.gradle -d
  - openssl aes-256-cbc -K $encrypted_9bcc98c17ce5_key -iv $encrypted_9bcc98c17ce5_iv
    -in conveyor/conveyor.keystore.enc -out conveyor/conveyor.keystore -d
  - gem update --system
  - bundle install
  
script:
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then fastlane deploy ; else fastlane checks ; fi

after_success:
  - bash <(curl -s https://codecov.io/bash)